Create interaction branch
sulaimonaa/to-do-list pull request #3
Opened 2023-06-17 12:27 UTC by sulaimonaa

#Add clear all task features
#Add completed features
#Add on-click method for completed and clear features

2023-06-17 13:05 UTC, t-yanick requested changes
# STATUS: CHANGES REQUIRED

Hi @sulaimonaa , 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  JavaScript file imported as module
:heavy_check_mark: Use of correct Github flow
:heavy_check_mark: Array method used

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-17 13:05 UTC, t-yanick commented on modules/taskFunctions.js
> +  }
- [ ] Great job working on this milestone.
- When I click on the checkbox to make task completed, the status does not change in the localstorage to completed:True.
- Secondly, I cannot tick the checkbox for more that one task. When I click the second, the first deselects.
- Finally when I click on `Clear all completed` even the tasks where the checkbox is not ticked are deleted. It is not supposed function like this.
![image](https://github.com/sulaimonaa/to-do-list/assets/62849872/9e758ac4-6b28-4afd-8b83-ba933acc14ed)

All these as per project requirements are supposed to work. Kindly look once one into these features

2023-06-17 21:14 UTC, prolajumokeoni approved these changes
Hi @sulaimonaa 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
  - All changes requested have been implemented 🥇  


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-17 21:33 UTC, merged

2023-06-28 10:00 UTC, Kanyorok commented
I have compared the code to best practices. You have a clean and quality flow of code 👍🏻. Keep up the good work. However, 😛 you could furnish the naming conventions so that they meet all the variable naming conventions of the code. Otherwise, good job 💯